### PR TITLE
Portuguese Translating

### PR DESCRIPTION
**Pull request by augustresende**
I would like to translate NiceHash into my native language, Portuguese. 

Portuguese is the language spoken in Brazil and Portugal. Portuguese is not Spanish.

Merge now

### CODE REVIEW

**Comment by augustresende** [comment]
@S74nk0

**Comment by augustresende** [comment]
@nicehashdev

**Comment by augustresende** [comment]
Hey!!! Please merge!

**Comment by S74nk0** [comment]
@AugustoResende Thanks for your contribution.

**Comment by augustresende** [comment]
:D

**Pull request merged**
