### PR TITLE
Implementation of Claymore's Ethereum miner

### PR DESCRIPTION
**Pull request by DillonN**
I added support for Claymore's eth miner - no dual algo or NVIDIA support though

It assumes the miner is in the bin_3rdparty folder under a folder called "claymore_ethereum"

I tried to keep any changes as similar to existing language as possible, but some abstraction needed to be added to ClaymoreBaseMiner since the eth miner handles some things differently than the Equihash/CN miners do (mainly reporting of hashrate as MH/s and no SSL support)

I also had to increase the benchmark time since 45s is barely enough to generate any hashes, required a bit of extra logic for the timer but I'm not sure if the "welcome to hell" comment was referring to anything else. Still at 45s for CN/Eq

Tested on two rigs, one with a Fury X and another with 2 290Xs, no issues

Issue #547

### CODE REVIEW

**Comment by keztheminer** [comment]
gg ,will never happen though with no nvida support ,amd is not to be supported don't u know that lol

**Comment by S74nk0** [comment]
@DillonN this is great, but unfortunately I have missed this pull request. ClaymoreDual has been added and now there are merge conflicts, really unfortunate for the duplicated work. The **"welcome to hell"** comment is that on some of the tests the miner would never finish (I really have no idea why as it makes no sense but it does seem that Claymore miners are heavily protected, they will not produce any hashes when there is a debugger present and so on...). I'll take a look at your contribution and make some changes where needed (i.e. Etherum benchmark time).

**Comment by DillonN** [comment]
No worries, I've been using a hackjob version of this for quite some time since I needed the extra temp control Claymore's miner can provide.

As for the benchmark thing, I needed to change something slightly to allow for >60s times. I've updated the pull request fork to only be this change so you can see exactly what I mean. I haven't tried it but it might allow longer times for the other Claymore miners as well.

Are you planning on implementing the dual decred mining feature too? That would be crazy, I gave up on it pretty quickly since it seems like a huge project.

**Comment by kenshirothefist** [comment]
Take a look here for the DUAL mode: https://github.com/nicehash/NiceHashMiner/wiki/Enable-ClaymoreDual-with-Decred-Lbry-Pascal

**Pull request closed without merging**
