### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by theLosers106**
- Check if the internet is available during startup
- Code improvements

### CODE REVIEW

**Comment by theLosers106** [comment]
@bitbandi Nope I must have missed that as I was looking for some cleaner way to do it. Thanks for the suggestion and it will be in the next commit. What is your opinion on should it be set globally (using EnvironmentVariableTarget) or just on a process basis?

**Comment by bitbandi** [comment]
@theLosers106 ah, i found better:
https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environmentvariables(v=vs.110).aspx
just add the two env variables before run the sgminer. (in QueryCDevs@sgminer.cs method, in BenchmarkStartProcess@Miner.cs and _Start@Miner.cs)

**Comment by theLosers106** [comment]
@bitbandi I think your first suggestion is the way to go as your second suggestion would not work on all cases because of: "If UseShellExecute is true, an InvalidOperationException is thrown when the Start method is called."

**Comment by bitbandi** [comment]
@theLosers106 ah, than use just the Environment.SetEnvironmentVariable for current process.

**Pull request merged**
